/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vitaltrack.gui;

/**
 *
 * @author Master
 */
public class PanelHistorial extends javax.swing.JPanel {
    private vitaltrack.modelo.Paciente paciente;
    private vitaltrack.logica.SistemaGestion sistema;
    private VentanaPrincipal ventana;
    private vitaltrack.logica.AnalizadorTendencias analizador;

    private javax.swing.table.DefaultTableModel modeloMediciones;
    private javax.swing.table.DefaultTableModel modeloAlertas;
    
    public PanelHistorial(vitaltrack.modelo.Paciente paciente, vitaltrack.logica.SistemaGestion sistema, VentanaPrincipal ventana) {
        initComponents();
        this.paciente = paciente;
        this.sistema = sistema;
        this.ventana = ventana;
        this.analizador = new vitaltrack.logica.AnalizadorTendencias(paciente.getHistorial());
        
        this.modeloMediciones = (javax.swing.table.DefaultTableModel) tablaMediciones.getModel();
        this.modeloAlertas = (javax.swing.table.DefaultTableModel) tablaAlertas.getModel();
        
        //Ejecutamos la carga médica inicial
        cargarDatos();
    }
    
    /**
     * Creates new form PanelHistorialN
     */
    public PanelHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblInfoPac = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMediciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAlertas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTendFC = new javax.swing.JLabel();
        lblTendSpo2 = new javax.swing.JLabel();
        lblAdvertencias = new javax.swing.JLabel();
        lblDiagnostico = new javax.swing.JLabel();
        btnAtender = new javax.swing.JButton();

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Historial Clinico");

        lblInfoPac.setText("Historia:  / Edad:  /Grupo sanguineo:  /Diagnostico:  ");

        tablaMediciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha y hora", "FC (bpm)", "Sp02 (%)", "Temp (°C)", "FR (rpm)", "PA", "Estado FC", "Estado Sp02"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMediciones);

        jLabel2.setText("Alertas de este paciente");

        tablaAlertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nivel", "Tipo", "Descripcion", "Fecha y hora", "Atendida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaAlertas);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tendencias:");

        lblTendFC.setText("FC: ");

        lblTendSpo2.setText("Sp02: ");

        lblAdvertencias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdvertencias.setText("Advertencias:");

        lblDiagnostico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiagnostico.setText("Diagnostico:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTendFC)
                    .addComponent(lblTendSpo2)
                    .addComponent(lblAdvertencias)
                    .addComponent(lblDiagnostico))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTendFC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTendSpo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAdvertencias)
                .addGap(56, 56, 56)
                .addComponent(lblDiagnostico)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        btnAtender.setText("Marcar como atendida");
        btnAtender.addActionListener(this::btnAtenderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfoPac)
                            .addComponent(lblTitulo)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtender)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoPac)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtender))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        ventana.mostrarDashboard();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        // TODO add your handling code here:
        int fila = tablaAlertas.getSelectedRow();
        if (fila >= 0 && fila < paciente.getHistorial().getAlertas().size()) {
            paciente.getHistorial().getAlertas().get(fila).setAtendida(true);
            cargarDatos();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una alerta de la tabla primero.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAtenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAdvertencias;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblInfoPac;
    private javax.swing.JLabel lblTendFC;
    private javax.swing.JLabel lblTendSpo2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaAlertas;
    private javax.swing.JTable tablaMediciones;
    // End of variables declaration//GEN-END:variables
    public void cargarDatos() {
        // Actualiza dinámicamente las etiquetas de cabecera con la ficha del paciente
        lblTitulo.setText("Historial clínico — " + paciente.getNombreCompleto());
        lblInfoPac.setText("Historia: " + paciente.getNroHistoriaClinica()
                + "  |  Edad: " + paciente.getEdad() + " años"
                + "  |  Grupo Sanguíneo: " + paciente.getGrupoSanguineo()
                + "  |  Diagnóstico: " + paciente.getDiagnostico());

        cargarMediciones();
        cargarAlertas();
        actualizarTendencias();
    }

    private void cargarMediciones() {
        modeloMediciones.setRowCount(0);
        java.util.List<vitaltrack.modelo.Medicion> lista = paciente.getHistorial().getMediciones();
        
        // Se cargan en orden inverso (la más reciente primero)
        for (int i = lista.size() - 1; i >= 0; i--) {
            vitaltrack.modelo.Medicion m = lista.get(i);
            
            Object[] fila = new Object[8];
            fila[0] = vitaltrack.utilidades.FormateadorFecha.formatearFechaHora(m.getTimestamp());
            fila[1] = String.format("%.0f", m.getFrecuenciaCardiaca());
            fila[2] = String.format("%.1f", m.getSaturacionO2());
            fila[3] = m.getTemperatura() > 0 ? String.format("%.1f", m.getTemperatura()) : "N/D";
            fila[4] = m.getFrecuenciaRespiratoria() > 0 ? String.format("%.0f", m.getFrecuenciaRespiratoria()) : "N/D";
            fila[5] = m.getPresionArterial();
            fila[6] = vitaltrack.logica.DiagnosticoAsistido.evaluarFC(m.getFrecuenciaCardiaca());
            fila[7] = vitaltrack.logica.DiagnosticoAsistido.evaluarSpo2(m.getSaturacionO2());

            modeloMediciones.addRow(fila);
        }
    }

    private void cargarAlertas() {
        modeloAlertas.setRowCount(0);
        java.util.List<vitaltrack.modelo.AlertaClinica> alertas = paciente.getHistorial().getAlertas();
        
        for (int i = 0; i < alertas.size(); i++) {
            vitaltrack.modelo.AlertaClinica a = alertas.get(i);
            
            Object[] fila = new Object[5];
            fila[0] = a.getNivelTexto();
            fila[1] = a.getTipoAlerta();
            fila[2] = a.getDescripcion();
            fila[3] = vitaltrack.utilidades.FormateadorFecha.formatearFechaHora(a.getTimestamp());
            fila[4] = a.isAtendida() ? "Sí ✔" : "No";

            modeloAlertas.addRow(fila);
        }
    }

    private void actualizarTendencias() {
        // Extraer tendencias algorítmicas del analizador clínico
        String tendFC = analizador.tendencia("FC");
        String tendSpo2 = analizador.tendencia("SPO2");

        lblTendFC.setText("FC: " + obtenerTextoDireccion(tendFC));
        lblTendSpo2.setText("SpO2: " + obtenerTextoDireccion(tendSpo2));

        // Actualizar área de advertencias críticas en formato HTML para quiebres de línea
        String adv = analizador.todasLasAdvertencias();
        if (adv.isEmpty()) {
            lblAdvertencias.setText("<html>Advertencias:<br>Sin advertencias activas</html>");
        } else {
            lblAdvertencias.setText("<html>Advertencias:<br>" + adv.replace("\n", "<br>") + "</html>");
        }

        // Evaluar la última telemetría para el Diagnóstico Asistido Automático
        vitaltrack.modelo.Medicion ultima = paciente.getHistorial().getUltimaMedicion();
        if (ultima != null) {
            String diag = vitaltrack.logica.DiagnosticoAsistido.evaluar(ultima);
            lblDiagnostico.setText("<html>Diagnóstico Asistido:<br>" + diag + "</html>");
        } else {
            lblDiagnostico.setText("<html>Diagnóstico Asistido:<br>Sin mediciones</html>");
        }
    }

    private String obtenerTextoDireccion(String tendencia) {
        if (tendencia.equals("SUBE")) {
            return "↑ Subiendo";
        } else if (tendencia.equals("BAJA")) {
            return "↓ Bajando";
        } else if (tendencia.equals("ESTABLE")) {
            return "→ Estable";
        } else {
            return "— Sin datos";
        }
    }
}
