/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vitaltrack.gui;

/**
 *
 * @author Master
 */
public class PanelPaciente extends javax.swing.JPanel {
    private vitaltrack.logica.SistemaGestion sistema;
    private VentanaPrincipal ventana;
    private javax.swing.table.DefaultTableModel modeloTabla;

    public PanelPaciente(vitaltrack.logica.SistemaGestion sistema, VentanaPrincipal ventana) {
        initComponents();
        this.sistema = sistema;
        this.ventana = ventana;
        
        // Vinculamos el modelo del lienzo visual a nuestra variable lógica
        this.modeloTabla = (javax.swing.table.DefaultTableModel) tabla.getModel();
        
        cargarDatos();
        configurarEventosManuales(); // Activa el doble clic
    }
    /**
     * Creates new form PanelPacienteN
     */
    public PanelPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnHistorial = new javax.swing.JButton();
        btnDiagnostico = new javax.swing.JButton();
        btnMonitor = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Pacientes registrados");

        btnNuevo.setText("Nuevo Paciente");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        jLabel1.setText("Selecciona un paciente para ver opciones");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Completo", "Num Cedula", "Edad", "Grupo", "Historia", "Monitor", "Diagnostico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnHistorial.setText("Ver historial");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        btnDiagnostico.setText("Asignar diagnostico");
        btnDiagnostico.addActionListener(this::btnDiagnosticoActionPerformed);

        btnMonitor.setText("Asignar monitor");
        btnMonitor.addActionListener(this::btnMonitorActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel2.setText("Selecciona una fila y luego el boton o hacer doble clic");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHistorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnDiagnostico)
                        .addGap(18, 18, 18)
                        .addComponent(btnMonitor)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistorial)
                    .addComponent(btnDiagnostico)
                    .addComponent(btnMonitor)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(421, 421, 421)
                            .addComponent(btnNuevo)
                            .addGap(6, 6, 6)))
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(btnNuevo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        DialogoRegistro dialogo = new DialogoRegistro(sistema);
        dialogo.setVisible(true);
        cargarDatos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        String id = getIdSeleccionado();
        if (id != null) {
            ventana.mostrarHistorialPaciente(id);
        }
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed
        // TODO add your handling code here:
        String id = getIdSeleccionado();
        if (id != null) {
            ventana.asignarDiagnostico(id);
            cargarDatos();
        }
    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    private void btnMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorActionPerformed
        // TODO add your handling code here:
        String id = getIdSeleccionado();
        if (id != null) {
            ventana.asignarMonitor(id);
            cargarDatos();
        }
    }//GEN-LAST:event_btnMonitorActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarSeleccionado();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnMonitor;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    public void cargarDatos() {
        modeloTabla.setRowCount(0);
        
        for (int i = 0; i < sistema.getPacientes().size(); i++) {
            vitaltrack.modelo.Paciente p = sistema.getPacientes().get(i);
            
            // Buscar de manera segura si tiene un monitor físico asignado
            String monitor = "Sin monitor";
            for (int j = 0; j < sistema.getMonitores().size(); j++) {
                vitaltrack.monitor.MonitorSignosVitales m = sistema.getMonitores().get(j);
                if (p.getId().equals(m.getIdPacienteAsignado())) {
                    monitor = m.getTipoMonitor().replace("Monitor ", "") + " (" + m.getIdMonitor() + ")";
                    break;
                }
            }

            Object[] fila = new Object[8];
            fila[0] = p.getId();
            fila[1] = p.getNombreCompleto();
            fila[2] = p.getCedNum();
            fila[3] = p.getEdad() + " años";
            fila[4] = p.getGrupoSanguineo();
            fila[5] = p.getNroHistoriaClinica();
            fila[6] = monitor;
            fila[7] = p.getDiagnostico();
            
            modeloTabla.addRow(fila);
        }
    }

    private String getIdSeleccionado() {
        int filaVisual = tabla.getSelectedRow();
        if (filaVisual < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccioná un paciente de la tabla primero.",
                "Sin selección", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
        int filaModelo = tabla.convertRowIndexToModel(filaVisual);
        return modeloTabla.getValueAt(filaModelo, 0).toString();
    }

    private void eliminarSeleccionado() {
        String id = getIdSeleccionado();
        if (id == null) {
            return;
        }

        vitaltrack.modelo.Paciente p = sistema.buscarPaciente(id);
        int conf = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Eliminar a " + p.getNombreCompleto() + " del sistema?\nSe perderá su historial clínico.",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);

        if (conf == javax.swing.JOptionPane.YES_OPTION) {
            sistema.eliminarPaciente(id);
            cargarDatos();
            ventana.setEstado("Paciente eliminado: " + p.getNombreCompleto());
        }
    }
    
    private void configurarEventosManuales() {
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    String id = getIdSeleccionado();
                    if (id != null) {
                        String nombre = sistema.buscarPaciente(id).getNombreCompleto();
                        String[] opciones = {"Ver historial", "Asignar diagnóstico",
                                             "Asignar monitor", "Asignar médico", "Cancelar"};

                        int opcion = javax.swing.JOptionPane.showOptionDialog(
                            PanelPaciente.this, "¿Qué deseas hacer?", nombre,
                            javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE,
                            null, opciones, opciones[0]
                        );

                        if (opcion == 0) ventana.mostrarHistorialPaciente(id);
                        if (opcion == 1) ventana.asignarDiagnostico(id);
                        if (opcion == 2) ventana.asignarMonitor(id);
                        if (opcion == 3) ventana.asignarMedico(id);
                    }
                }
            }
        });
    }
}
