/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vitaltrack.gui;

/**
 *
 * @author Master
 */
public class SimuladorMedicion extends javax.swing.JPanel {

    private vitaltrack.logica.SistemaGestion sistema;
    private VentanaPrincipal ventana;

    public SimuladorMedicion(vitaltrack.logica.SistemaGestion sistema, VentanaPrincipal ventana) {
        initComponents();
        this.sistema = sistema;
        this.ventana = ventana;
        
        // Carga inicial y enganche de listeners manuales
        cargarPacientes();
        configurarEventosManuales();
    }
    
    /**
     * Creates new form SimuladorMedicion
     */
    public SimuladorMedicion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPaciente = new javax.swing.JComboBox<>();
        lblMonitorAsignado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFC = new javax.swing.JTextField();
        txtSpo2 = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtFR = new javax.swing.JTextField();
        txtPAS = new javax.swing.JTextField();
        txtPAD = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Simulador de Mediciones");

        jLabel2.setText("Puedes ingresar valores manualmente o generar una medicion automatica");

        jLabel1.setText("Selecciona un paciente");

        cmbPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaciente.addActionListener(this::cmbPacienteActionPerformed);

        lblMonitorAsignado.setText("Monitor:");

        jLabel3.setText("FC (%)");

        jLabel4.setText("Sp02 (%)");

        jLabel5.setText("Temperatura (°C)");

        jLabel6.setText("Frec. resp.");

        jLabel7.setText("PA sistolica");

        jLabel8.setText("PA diastolica");

        txtFC.addActionListener(this::txtFCActionPerformed);

        btnGenerar.setText("Generar Automatico");
        btnGenerar.addActionListener(this::btnGenerarActionPerformed);

        btnManual.setText("Registrar Manual");
        btnManual.addActionListener(this::btnManualActionPerformed);

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel9.setText("Resultado de la medición");

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setLineWrap(true);
        txtResultado.setRows(5);
        txtResultado.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTemp)
                                    .addComponent(txtFC)
                                    .addComponent(txtSpo2)
                                    .addComponent(txtPAD)
                                    .addComponent(txtFR, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPAS, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnGenerar)
                                .addGap(65, 65, 65)
                                .addComponent(btnManual)
                                .addGap(54, 54, 54)
                                .addComponent(btnLimpiar)
                                .addGap(0, 193, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(lblMonitorAsignado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonitorAsignado)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSpo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManual)
                            .addComponent(btnLimpiar)
                            .addComponent(btnGenerar))
                        .addGap(35, 35, 35))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPacienteActionPerformed
        // TODO add your handling code here:
        actualizarMonitorInfo();
    }//GEN-LAST:event_cmbPacienteActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        generarAutomatico();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        // TODO add your handling code here:
        registrarManual();
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnManual;
    private javax.swing.JComboBox<String> cmbPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMonitorAsignado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFC;
    private javax.swing.JTextField txtFR;
    private javax.swing.JTextField txtPAD;
    private javax.swing.JTextField txtPAS;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtSpo2;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables

    private void generarAutomatico() {
        vitaltrack.modelo.Paciente paciente = getPacienteSeleccionado();
        if (paciente == null) return;

        vitaltrack.monitor.MonitorSignosVitales monitor = getMonitorDePaciente(paciente.getId());
        if (monitor == null) {
            mostrarError("Este paciente no tiene un monitor asignado.\nAsignale uno desde el panel de Pacientes.");
            return;
        }

        vitaltrack.modelo.Medicion medicion = monitor.medir();
        paciente.agregarMedicion(medicion);

        vitaltrack.modelo.AlertaClinica alerta = evaluarMonitor(monitor, medicion, paciente.getId());
        if (alerta != null) {
            paciente.getHistorial().agregarAlerta(alerta);
        }

        mostrarResultado(medicion, alerta, monitor.getTipoMonitor(), true);
        rellenarCampos(medicion);
        ventana.setEstado("Medición automática registrada para " + paciente.getNombreCompleto());
    }

    private void registrarManual() {
        vitaltrack.modelo.Paciente paciente = getPacienteSeleccionado();
        if (paciente == null) return;

        if (!vitaltrack.utilidades.ValidadorDatos.esDecimalEnRango(txtFC.getText(), 0, 300)) {
            mostrarError("FC inválida. Ingresá un valor entre 0 y 300."); return;
        }
        if (!vitaltrack.utilidades.ValidadorDatos.esDecimalEnRango(txtSpo2.getText(), 0, 100)) {
            mostrarError("SpO2 inválida. Ingresá un valor entre 0 y 100."); return;
        }

        double fc = Double.parseDouble(txtFC.getText().trim());
        double spo2 = Double.parseDouble(txtSpo2.getText().trim());
        double temp = parsearOpcional(txtTemp.getText());
        double fr = parsearOpcional(txtFR.getText());
        String pas = txtPAS.getText().trim().isEmpty() ? "N/D" : txtPAS.getText().trim();
        String pad = txtPAD.getText().trim().isEmpty() ? "N/D" : txtPAD.getText().trim();

        String idMed = vitaltrack.utilidades.GeneradorId.generar("MED");
        vitaltrack.modelo.Medicion medicion = new vitaltrack.modelo.Medicion(idMed, fc, spo2, temp, fr, pas, pad);
        paciente.agregarMedicion(medicion);

        vitaltrack.monitor.MonitorSignosVitales monitor = getMonitorDePaciente(paciente.getId());
        vitaltrack.modelo.AlertaClinica alerta = null;
        if (monitor != null) {
            alerta = evaluarMonitor(monitor, medicion, paciente.getId());
            if (alerta != null) {
                paciente.getHistorial().agregarAlerta(alerta);
            }
        }

        mostrarResultado(medicion, alerta, monitor != null ? monitor.getTipoMonitor() : "Ingreso manual", false);
        ventana.setEstado("Medición manual registrada para " + paciente.getNombreCompleto());
    }

    private vitaltrack.modelo.AlertaClinica evaluarMonitor(vitaltrack.monitor.MonitorSignosVitales monitor, vitaltrack.modelo.Medicion medicion, String idPaciente) {
        if (monitor instanceof vitaltrack.monitor.MonitorUCI) {
            vitaltrack.monitor.MonitorUCI uci = (vitaltrack.monitor.MonitorUCI) monitor;
            vitaltrack.modelo.AlertaClinica a = uci.evaluarYGenerar(medicion, idPaciente);
            return a != null ? a : uci.evaluarParametrosUCI(idPaciente);
        } else if (monitor instanceof vitaltrack.monitor.MonitorAvanzado) {
            return ((vitaltrack.monitor.MonitorAvanzado) monitor).evaluarYGenerar(medicion, idPaciente);
        } else if (monitor instanceof vitaltrack.monitor.MonitorBasico) {
            return ((vitaltrack.monitor.MonitorBasico) monitor).evaluarYGenerar(medicion, idPaciente);
        }
        return null;
    }

    private void mostrarResultado(vitaltrack.modelo.Medicion m, vitaltrack.modelo.AlertaClinica alerta, String tipoMonitor, boolean automatico) {
        StringBuilder sb = new StringBuilder();
        sb.append("===================================\n");
        sb.append("      ESCANEO MÉDICO    \n");
        sb.append("===================================\n\n");
        sb.append("Origen: ").append(automatico ? "Automático (Sensor)" : "Manual").append("\n");
        sb.append("Monitor: ").append(tipoMonitor).append("\n");
        sb.append("ID Medición: ").append(m.getIdMedicion()).append("\n\n");
        
        sb.append("SIGNOS VITALES:\n");
        sb.append("  FC: ").append(String.format("%.0f bpm\n", m.getFrecuenciaCardiaca()));
        sb.append("  SpO2: ").append(String.format("%.1f %%\n", m.getSaturacionO2()));
        
        if (m.getTemperatura() > 0) sb.append("  Temp: ").append(String.format("%.1f °C\n", m.getTemperatura()));
        if (m.getFrecuenciaRespiratoria() > 0) sb.append("  FR: ").append(String.format("%.0f rpm\n", m.getFrecuenciaRespiratoria()));
        if (!"N/D".equals(m.getPresionArterialSist())) sb.append("  PA: ").append(m.getPresionArterial()).append("\n");

        sb.append("\n");

        String diagnosticoRobot = vitaltrack.logica.DiagnosticoAsistido.evaluar(m);
        
        sb.append("ANÁLISIS DE SINTOMATOLOGÍA:\n");
        if (!diagnosticoRobot.isEmpty()) {
            sb.append("  ").append(diagnosticoRobot).append("\n\n");
        } else {
            sb.append("  No se detectan patrones de riesgo clínico inmediato.\n\n");
        }

        if (alerta != null) {
            sb.append("ALERTA DETECTADA:\n");
            sb.append("  Nivel: ").append(alerta.getNivelTexto()).append("\n");
            sb.append("  Tipo: ").append(alerta.getTipoAlerta()).append("\n");
            sb.append("  Detalle: ").append(alerta.getDescripcion()).append("\n");
        } else {
            sb.append("Valores estables bajo rangos normales.\n");
        }
        
        txtResultado.setText(sb.toString());
    }

    private void rellenarCampos(vitaltrack.modelo.Medicion m) {
        txtFC.setText(String.format("%.0f", m.getFrecuenciaCardiaca()));
        txtSpo2.setText(String.format("%.1f", m.getSaturacionO2()));
        txtTemp.setText(m.getTemperatura() > 0 ? String.format("%.1f", m.getTemperatura()) : "");
        txtFR.setText(m.getFrecuenciaRespiratoria() > 0 ? String.format("%.0f", m.getFrecuenciaRespiratoria()) : "");
        txtPAS.setText(!"N/D".equals(m.getPresionArterialSist()) ? m.getPresionArterialSist() : "");
        txtPAD.setText(!"N/D".equals(m.getPresionArterialDias()) ? m.getPresionArterialDias() : "");
    }

    private void limpiarCampos() {
        txtFC.setText(""); txtSpo2.setText(""); txtTemp.setText("");
        txtFR.setText("");  txtPAS.setText("");  txtPAD.setText("");
        txtResultado.setText("Campos listos para una nueva medición.");
    }

    private void mostrarError(String msg) {
        txtResultado.setText("ERROR CLÍNICO\n\n" + msg);
    }

    public void cargarPacientes() {
        cmbPaciente.removeAllItems();
        if (sistema.getPacientes().isEmpty()) {
            cmbPaciente.addItem("— Sin pacientes registrados —");
            return;
        }
        for (int i = 0; i < sistema.getPacientes().size(); i++) {
            vitaltrack.modelo.Paciente p = sistema.getPacientes().get(i);
            cmbPaciente.addItem(p.getId() + " — " + p.getNombreCompleto());
        }
        actualizarMonitorInfo();
    }

    private void actualizarMonitorInfo() {
        vitaltrack.modelo.Paciente p = getPacienteSeleccionado();
        if (p == null) { lblMonitorAsignado.setText("Monitor: —"); return; }
        vitaltrack.monitor.MonitorSignosVitales m = getMonitorDePaciente(p.getId());
        if (m != null) {
            lblMonitorAsignado.setText("Monitor asignado: " + m.getTipoMonitor() + " (" + m.getIdMonitor() + ")");
        } else {
            lblMonitorAsignado.setText("Sin monitor clínico asignado");
        }
    }

    private vitaltrack.modelo.Paciente getPacienteSeleccionado() {
        if (cmbPaciente.getSelectedItem() == null) return null;
        String sel = cmbPaciente.getSelectedItem().toString();
        if (sel.startsWith("—")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay pacientes válidos seleccionados.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return null;
        }
        String id = sel.split(" — ")[0];
        return sistema.buscarPaciente(id);
    }

    private vitaltrack.monitor.MonitorSignosVitales getMonitorDePaciente(String idPaciente) {
        for (int i = 0; i < sistema.getMonitores().size(); i++) {
            vitaltrack.monitor.MonitorSignosVitales m = sistema.getMonitores().get(i);
            if (idPaciente.equals(m.getIdPacienteAsignado())) return m;
        }
        return null;
    }

    private double parsearOpcional(String texto) {
        try { return Double.parseDouble(texto.trim()); } 
        catch (Exception e) { return 0.0; }
    }
    
    private void configurarEventosManuales() {
        
    }
}
